language: julia
services:
   - mysql
os:
  - linux
  - osx
julia:
  - 0.5
notifications:
  email: true
before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then . ./ci/travis/before_install-osx.sh; fi
  - export OLD_PATH=$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`mysql_config --libs | cut -d ' ' -f1 | sed 's/-L//'`
  - echo $LD_LIBRARY_PATH
after_script:
  - export LD_LIBRARY_PATH=$OLD_PATH
  - unset OLD_PATH
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("BioMedQuery"); Pkg.test("BioMedQuery"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("BioMedQuery")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("BioMedQuery")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
