language: julia
os:
- linux
- osx
julia:
- 0.4
- release
notifications:
  email: false
script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia -e 'Pkg.clone(pwd()); Pkg.build("NLM"); Pkg.test("NLM"; coverage=true)'
before_install:
- openssl aes-256-cbc -K $encrypted_87475759314c_key -iv $encrypted_87475759314c_iv
  -in credentials.txt.enc -out credentials.txt -d
- ls
