site_name:        BioMedQuery.jl
repo_url:         https://github.com/bcbi/BioMedQuery.jl
site_description: Julia connection to BioMedial Search APIs
site_author:      bcbi

theme: material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  # - mdx_math

docs_dir: 'build'

pages:
- Overview: index.md
- Entrez: entrez.md
- UMLS: umls.md
- Clinical Trials: ct.md
- Processes/Workflows: processes.md
- Sample Scripts: examples.md
- Database Utilities: dbutils.md
- Library: library.md

extra:
  logo: 'images/bcbi_logo.jpeg'
