site_name:        BioMedQuery.jl
site_author:      Isabel Restrepo
repo_url:         https://github.com/bcbi/BioMedQuery.jl
site_description: Julia connection to BioMedial Search APIs
site_author:      bcbi

theme: 
  name: 'material'
  # logo: 'images/bcbi_logo.jpeg'

extra_css:
  - assets/Documenter.css

# extra_javascript:
#   - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#   - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite

  # - mdx_math

docs_dir: 'build'

pages:
- Home: index.md
- Examples: 
  - Overview: examples.md
  - Pubmed Search and Save: example1.md
  - MeSH/UMLS Map: example2.md
  - UMLS Semantic Filtering: example3.md
  - Export to citations: example4.md
- Manual:
  - Processes/Workflows: processes.md
  - PubMed: pubmed.md
  - Clinical Trials: ct.md
  - Database Utilities: dbutils.md
  - Library: library.md
  
