site_name:        BioMedQuery.jl
repo_url:         https://github.com/bcbi/BioMedQuery.jl
site_description: Julia connection to BioMedial Search APIs
site_author:      bcbi

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Overview: index.md
